name: Github Actions CI
on: [push]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-project
      - name: Run ESLint
        run: npm run lint

  unit-test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: ./.github/actions/setup-project
      - name: Run Vitest
        run: npm test

  integration-test:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: ./.github/actions/setup-project
      - name: Run Integration Tests
        run: echo "Hello Integration !"

  e2e-test:
    runs-on: ubuntu-latest
    needs: integration-test
    steps:
      - uses: ./.github/actions/setup-project
      - name: Run E2E Tests
        run: echo "Hello E2E !"

  only-canary:
    runs-on: ubuntu-latest
    if: vars.ENV_TARGET == 'canary'
    steps:
      - name: Canary
        run: echo "HEllo Only Canary!"
